### ISSUE TITLE
Why not python-aptly?

### ISSUE THREAD

**Issue by fpytloun** [TimSusa/aptly_api_cli#1]
Hello,

just a little question - why didn't you use [python-aptly](https://github.com/tcpcloud/python-aptly) as a base for extending and started a new project instead?
Most of your features would be easy to merge:
- extending the api with high level classes which is nice (but I would better generate such classes from api definition in the same manner as python foreman is done)
- and tooling in the same way as `aptly.publisher`

**Comment by TimSusa** [comment]
Hello fpytloun, 

at first thanks for your feedback! Our project was some kind of historical grown. We have decided to explore aptly and its functionalities at a first shot and then to start our own tailor-made application for integration into our own special CI Workflow. Afterwards, we decided to make all this available to the community. Yes, I had discovered your project a meanwhile ago, but at this time our approach was already started internally and the app was born introducing our own requirements (for JENKINS). Furthermore, I could not see at that time, where your application was able to find solutions for our special problems (respect our nomenclature for package names, clean out old packages and snapshots in clean working way or do that stuff that we already put into our CI-bashscripts, integrating into our workflow on JENKINS, dependent on further JENKINS Plugins). Furthermore, we gave ourselves the pressure to come up with working solutions, which work on production for our own special needs. 

However, you mentioned two very interesting points. At first:  Generate such classes from api definition in the same manner as python foreman is done) and second:  the tooling in the same way as aptly.publisher does. 

So my question for you would be: How would you do that and would there be a way, where we could merge our applications into a single one, without losing the benefit of both? 

Best, 

Tim Susa.

**Comment by fpytloun** [comment]
I maybe don't fully understand what's your exact workflow but it seems that aptly-publisher does at least something very similar:
- creates multi-component publishes from YAML describing what to publish and how
- can merge snapshots from multiple sources and publish as single component (eg. merge debian's main contrib and non-free sources and publish simply as main component)
- can do diffs between publishes (not only snapshots)
- promotes whole components or selected packages between publishes (so user doesn't have to work with snapshots directly)
- handles cleanup of unused snapshots

I think that workflow picture on tcpcloud/python-aptly page shows how it was supposed to be used.

What it doesn't have is CLI to all Aptly methods (which would be great to have - full featured REST API client in Python). The reason is simple - it may be difficult to maintain it on every aptly API change. That's why I wanted to use same approach as python-foreman - make machine-readable API model, maintained by aptly developers and provided by API itself. Python client would then download model on initialization and use it to create objects and methods. Which seems to be very effective and elegant approach to do REST API clients.

At the moment remaining tasks are done by simple curl as in our Jenkins jobs:
https://github.com/tcpcloud/jenkins-jobs/tree/master/aptly
https://github.com/tcpcloud/jenkins-jobs/blob/master/debian-build/jobs.yaml#L170

and script that updates mirrors and creates nightly snapshots:
https://github.com/tcpcloud/salt-formula-aptly/blob/master/aptly/files/aptly_mirror_update.sh

**Comment by TimSusa** [comment]
Sry about the delay, 

..and sry that I do not have enough time to get a full answer to yours, but I try to assume short two points:
1. Totally get rid of using curl in scripts. Use our aptly-api-cli. 
2. I think we have a different approach/philosophy about the basic workflow, but I will investigate more time to understand, perspectively.
